apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260614-234616-xvjo24b0532r-service
spec:
  selector:
    app: enterprise-system-20260614-234616-xvjo24b0532r
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
